Project

In [1]:
import pandas as pd

# Load dataset
df = pd.read_csv("Online Sales Data.csv")

# Display first few rows
df.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [2]:
# Number of rows and columns
df.shape

# Column names and data types
df.info()

# Summary statistics for numerical columns
df.describe()

# Check unique values for categorical columns
df.select_dtypes(include="object").nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    240 non-null    int64
 1   Date              240 non-null    object
 2   Product Category  240 non-null    object
 3   Product Name      240 non-null    object
 4   Units Sold        240 non-null    int64
 5   Unit Price        240 non-null    float64
 6   Total Revenue     240 non-null    float64
 7   Region            240 non-null    object
 8   Payment Method    240 non-null    object
dtypes: float64(2), int64(2), object(5)
memory usage: 17.0+ KB

Date                240
Product Category      6
Product Name        232
Region                3
Payment Method        3
dtype: int64

In [3]:
df.isnull().sum()

Transaction ID      0
Date                0
Product Category    0
Product Name        0
Units Sold          0
Unit Price          0
Total Revenue       0
Region              0
Payment Method      0
dtype: int64

In [5]:
# Recalculate total price
df["Calculated Total"] = df["Units Sold"] * df["Unit Price"]

# Identify incorrect total price values
incorrect_total = df[df["Total Revenue"] != df["Calculated Total"]]

# Replace incorrect values
df.loc[df["Total Revenue"] != df["Calculated Total"], "Total Revenue"] = df["Calculated Total"]

# Drop helper column
df.drop(columns=["Calculated Total"], inplace=True)

In [6]:
# Check duplicates
df.duplicated().sum()

# Remove duplicate rows
df.drop_duplicates(inplace=True)

In [9]:
df["Date"] = pd.to_datetime(df["Date"])

df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day

In [ ]:
# df["Sales Level"] = pd.cut(
#     df["Total Price"],
#     bins=[0, 100, 500, df["Total Price"].max()],
#     labels=["Low", "Medium", "High"]
# )

In [10]:
df.info()
df.describe()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    240 non-null    int64
 1   Date              240 non-null    datetime64[ns]
 2   Product Category  240 non-null    object
 3   Product Name      240 non-null    object
 4   Units Sold        240 non-null    int64
 5   Unit Price        240 non-null    float64
 6   Total Revenue     240 non-null    float64
 7   Region            240 non-null    object
 8   Payment Method    240 non-null    object
 9   Year              240 non-null    int32
 10  Month             240 non-null    int32
 11  Day               240 non-null    int32
dtypes: datetime64[ns](1), float64(2), int32(3), int64(2), object(4)
memory usage: 19.8+ KB

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Year,Month,Day
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,2024,1,1
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,2024,1,2
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,2024,1,3
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,2024,1,4
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,2024,1,5

In [13]:
# Select numeric columns only
numeric_df = df.select_dtypes(include=["int64", "float64"])

In [15]:
stats_summary = pd.DataFrame({
    "Mean": numeric_df.mean(),
    "Sum": numeric_df.sum(),
    "Min": numeric_df.min(),
    "Max": numeric_df.max(),
    "Range": numeric_df.max() - numeric_df.min(),
    "Median": numeric_df.median(),
    "Std Dev": numeric_df.std()
})

stats_summary

,Mean,Sum,Min,Max,Range,Median,Std Dev
Transaction ID,10120.500000,2428920.00,10001.0,10240.00,239.00,10120.50,69.426220
Units Sold,2.158333,518.00,1.0,10.00,9.00,2.00,1.322454
Unit Price,236.395583,56734.94,6.5,3899.99,3893.49,89.99,429.446695
Total Revenue,335.699375,80567.85,6.5,3899.99,3893.49,179.97,485.804469

In [16]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

In [19]:
fig = px.histogram(
    df,
    x="Total Revenue",
    nbins=30,
    title="Distribution of Total Sales Amount",
    hover_data=["Product Category", "Region"]
)

fig.show()

In [21]:
fig = px.scatter(
    df,
    x="Units Sold",
    y="Total Revenue",
    color="Product Category",
    size="Unit Price",
    hover_data=["Product Name", "Region", "Payment Method"],
    title="Relationship Between Quantity Sold and Total Revenue"
)

fig.show()

In [24]:
category_sales = df.groupby("Product Category")["Total Revenue"].sum().reset_index()

fig = px.bar(
    category_sales,
    x="Product Category",
    y="Total Revenue",
    title="Total Revenue by Product Category",
    hover_data=["Total Revenue"]
)

fig.show()

In [25]:
fig = px.scatter(
    df,
    x="Units Sold",
    y="Total Revenue",
    color="Region",
    hover_data=["Product Name", "Product Category"],
    title="Sales Relationship by Region"
)

fig.update_layout(
    updatemenus=[
        {
            "buttons": [
                {
                    "label": region,
                    "method": "update",
                    "args": [
                        {"visible": df["Region"] == region},
                        {"title": f"Sales Relationship in {region}"}
                    ]
                }
                for region in df["Region"].unique()
            ],
            "direction": "down"
        }
    ]
)

fig.show()

In [26]:
daily_sales = df.groupby("Date")["Total Revenue"].sum().reset_index()

fig = px.line(
    daily_sales,
    x="Date",
    y="Total Revenue",
    title="Sales Trend Over Time"
)

fig.update_xaxes(rangeslider_visible=True)

fig.show()

In [28]:
payment_sales = df.groupby("Payment Method")["Total Revenue"].mean().reset_index()

fig = px.bar(
    payment_sales,
    x="Payment Method",
    y="Total Revenue",
    title="Average Transaction Value by Payment Method",
    hover_data=["Total Revenue"]
)

fig.show()

In [29]:
import plotly.express as px

# Aggregate total sales by region
region_sales = df.groupby("Region")["Total Revenue"].sum().reset_index()

region_sales

          Region  Total Revenue
0           Asia       22455.45
1         Europe       21268.06
2  North America       36844.34

In [30]:
fig = px.choropleth(
    region_sales,
    locations="Region",
    locationmode="continent names",
    color="Total Revenue",
    hover_name="Region",
    hover_data={"Total Revenue": True},
    color_continuous_scale="Blues",
    title="Total Sales Revenue by Region"
)

fig.show()

ValueError:
    Invalid value of type 'builtins.str' received for the 'locationmode' property of choropleth
        Received value: 'continent names'

    The 'locationmode' property is an enumeration that may be specified as:
      - One of the following enumeration values:
            ['ISO-3', 'USA-states', 'country names', 'geojson-id']